### ISSUE TITLE
The info.plist can't be found ,build failed.Is there any way to solve it?

### ISSUE THREAD

**Issue by lmyl** [attaswift/Attabench#10]
could not read data from '/Users/ly/Attabench/Benchmarking/BenchmarkIPC/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.
All the files in the folder(BenchmarkIPC and Benchmarking) do not exist.
Is there any way to solve it?

**Comment by lmyl** [comment]
And compiler error.  In AttabenchDocument.swift, Cannot convert value of type 'RunOptions' to expected argument type 'RunOptions'. I check that options of type is RunOptions ,but compiler error,I use Xcode 9.2

**Comment by lmyl** [comment]
Ok，I solve it successfully . Thank the author for providing very good performance testing tools.

**Comment by juraj-blahunka** [comment]
Just came across the same build issue as well, the resolution was to fetch the submodule via
```
git submodule init 
git submodule update
```

**Comment by fishmanlol** [comment]
I met a problem happen in
> carthage bootstrap --platform Mac
and i get the following output:

ty:Attabench ty$ carthage bootstrap --platform Mac
*** Checking out SipHash at "7f83e142126db134b8d9175cb98b65ba95c18a1f"
*** Checking out BTree at "9e34b5311b0d44846d91245b8361a42d7e06275a"
*** Checking out OptionParser at "049f1e2b9d4550c25d99c54e17a045149e723afb"
*** Checking out BigInt at "b4bfe356e9bd76c59e0781d8584c495ab348b1f6"
*** Checking out GlueKit at "a1283dba1d57578e34ded41bd9b5f24a2b9bf72f"
*** Checking out SipHash at "7f83e142126db134b8d9175cb98b65ba95c18a1f"
*** xcodebuild output can be found in /var/folders/l7/ygr6fwz521b5rgwd_n6brxrr0000gn/T/carthage-xcodebuild.WQegpO.log
*** Building scheme "BTree-PerformanceTests" in BTree.xcodeproj
*** Building scheme "BTree-macOS" in BTree.xcodeproj
*** Building scheme "OptionParser" in OptionParser.xcodeproj
*** Building scheme "SipHash-macOS" in SipHash.xcodeproj
*** Building scheme "BigInt-macOS" in BigInt.xcworkspace
*** Building scheme "GlueKit-PerformanceTests" in GlueKit.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/ty/Attabench/Carthage/Checkouts/GlueKit/GlueKit.xcworkspace -scheme GlueKit-PerformanceTests -configuration Release -derivedDataPath /Users/ty/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/GlueKit/a1283dba1d57578e34ded41bd9b5f24a2b9bf72f ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l7/ygr6fwz521b5rgwd_n6brxrr0000gn/T/GlueKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/ty/Attabench/Carthage/Checkouts/GlueKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l7/ygr6fwz521b5rgwd_n6brxrr0000gn/T/carthage-xcodebuild.WQegpO.log

I have no ideal how to handle it, thanks in advance.
