### ISSUE TITLE
Benchmarking git submodule not cloning

### ISSUE THREAD

**Issue by cserban** [attaswift/Attabench#8]
Hi, 
by cloning Attabench repository (folowing the installation step 1) i was not able to build the project.
It was required to manually add the files from Benchmarking submodule.

Am i the only one with this issue?

**Comment by vanyaland** [comment]
@cserban by adding `--recursive` option solves the issue for me:

```bash
git clone https://github.com/attaswift/Attabench.git --recursive
```

**Comment by lorentey** [comment]
Thank you!
